### PR TITLE
vfio/device: add support enabling/disabling specific IRQ(s)

### PR DESCRIPTION
**Pull request by minwooim**

### CODE REVIEW

**Comment by birkelund** [comment]
I would be OK with an API breakage here for next major version. Just replace the existing functions with one including a `start` parameter.

**Comment by minwooim** [comment]
> I would be OK with an API breakage here for next major version. Just replace the existing functions with one including a `start` parameter.

`vfio_set_irq()` can be simply converted to have a new parameter `start`, but `vfio_disable_irq()` has been used to disable *ALL* IRQs.  How about rename `vfio_disable_irq` to `vfio_disable_irq_all` or something like that? If so, we can make `vfio_disable_irq` disables with targeting `start` for `count`.

> 
> Please add a note in `CHANGELOG.md` for this.

Okay!

**Comment by birkelund** [comment]
> > I would be OK with an API breakage here for next major version. Just replace the existing functions with one including a `start` parameter.
> 
> `vfio_set_irq()` can be simply converted to have a new parameter `start`, but `vfio_disable_irq()` has been used to disable _ALL_ IRQs. How about rename `vfio_disable_irq` to `vfio_disable_irq_all` or something like that? If so, we can make `vfio_disable_irq` disables with targeting `start` for `count`.

Sounds good!

**Comment by minwooim** [comment]
Updated branch.

**Pull request merged**
